version: '3.3'

services:
  mailhog:
    image: mailhog/mailhog
    ports: 
     - 1025:1025 # smtp server
     - 8025:8025 # web ui
  nginx:
    build: ./nginx
    ports:
      - "8083:80"
    depends_on:
      - php-fpm
    volumes:
      - ./index.php:/var/www/html/index.php
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_DATABASE: 'training'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  php-fpm:
    build: .
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./PHPMailer:/var/www/html/PHPMailer
volumes:
  db_data: {}
